import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import OnScreenNav from "@/components/ScreenNav/OnScreenNav";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Corporate xyz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en" style={{scrollbarColor: "#5eead4 #0f766e" ,scrollbarWidth: "thin",scrollBehavior:"smooth"}}>
      <html lang="en" style={{scrollbarWidth:"none"}}>
      <body className={`${inter.className} flex flex-col min-h-screen`} >
        <div className="bg-transparent fixed z-50 w-full"> 
          <Navbar />
        </div>
        <div className="flex-1 flex flex-col" >
          {children}
        </div>
        <div>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
